### ISSUE TITLE
components layout flow broken

### ISSUE THREAD

**Issue by pgte** [paz-sh/paz-sh.github.io#2]
![paz_-_continuous_deployment_for_production_environments](https://cloud.githubusercontent.com/assets/47910/6443451/de44a592-c0ee-11e4-8a96-98c8bdd45b2f.png)

Firefox 36.0 on Mac

**Comment by lukebond** [comment]
@jongold is this easy to fix?

**Comment by lukebond** [comment]
looks good now thanks @jongold
