### ISSUE TITLE
Implement tabs for Presentations section

### ISSUE THREAD

**Issue by jem-computer** [paz-sh/paz-sh.github.io#7]
Didn't need to code it yet because there's only one video, this needs to be done as soon as the LNUG video is released.

**Comment by lukebond** [comment]
the LNUG presentation video is up: https://www.youtube.com/watch?v=cQOPoDmkFg8

**Comment by lukebond** [comment]
took a stab at it and failed https://github.com/paz-sh/paz-sh.github.io/commit/0f1fc9ea1ca1404bd2fa17fce01984f09cc40261#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by jem-computer** [comment]
Closed #11
